{
 "title": "Loki compactor",
 "tags": [
  "loki",
  "monitoring loki",
  "prometheus",
  "compactor"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Compact and Mark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Compact and Mark Operation Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_last_successful_run_timestamp_seconds * 1000"
    }
   ]
  },
  {
   "title": "Compact and Mark Operations Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_duration_seconds"
    }
   ]
  },
  {
   "title": "Compact and Mark Operations Per Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_compact_tables_operation_total[$__rate_interval]))"
    }
   ]
  },
  { "title": "Per Table Marker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processed Tables Per Action",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(action)(loki_boltdb_shipper_retention_marker_table_processed_total)"
    }
   ]
  },
  {
   "title": "Modified Tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(table,action)(loki_boltdb_shipper_retention_marker_table_processed_total)"
    }
   ]
  },
  {
   "title": "Marks Creation Rate Per Table",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table)(rate(loki_boltdb_shipper_retention_marker_count_total[$__rate_interval])) >0"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Marked Chunks (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_marker_count_total[24h]))"
    }
   ]
  },
  {
   "title": "Mark Table Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_bucket[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "{{le}}"
    },
    {},
    {}
   ]
  },
  { "title": "Sweeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Delete Chunks (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count[24h]))"
    }
   ]
  },
  {
   "title": "Delete Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_sum[$__rate_interval])) * 1000 / sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count[$__rate_interval]))"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket[$__rate_interval])) by (le)) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket[$__rate_interval])) by (le)) * 1000"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Sweeper Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - (loki_boltdb_shipper_retention_sweeper_marker_file_processing_current_time > 0)"
    }
   ]
  },
  {
   "title": "Marks Files to Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_boltdb_shipper_retention_sweeper_marker_files_current)"
    }
   ]
  },
  {
   "title": "Delete Rate Per Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count[$__rate_interval]))"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}