{
 "title": "Loki  monitoring (Promtail, Loki)",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki. Memory and CPU usage of Promtail/Loki compared against the Kubernetes memory/cpu limits and requests.",
 "tags": [
  "tools",
  "loki",
  "prometheus",
  "monitoring loki"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Problems in the Loki Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of error/warning messages logged by Loki itself",
   "type": "timeseries",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_log_messages_total{level=~\"error|warn\"})[1m]) by (level,app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "{source=\"log\",k8s_app=~\"loki.+\"} |= \"level\" != \"debug\" != \"info\""
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "timeseries",
   "description": "Total number of messages logged by Promtail",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_log_messages_total{level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "{source=\"log\", k8s_app=~\"promtail\"} |= \"level\" != \"debug\" != \"info\""
    }
   ]
  },
  {
   "title": "Loki (distributor) - failed batch appends sent to ingesters",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total[1m])*60",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Promtail - dropped log entries",
   "type": "graph",
   "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_dropped_entries_total[1m])*60",
     "legendFormat": "pod={{kubernetes_pod_name}}, instance={{instance}}"
    }
   ]
  },
  { "title": "Logging activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Number of Streams in Loki",
   "type": "graph",
   "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
   ]
  },
  {
   "title": "Loki (distributor) - log entries received per second",
   "type": "graph",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m])"
    }
   ]
  },
  {
   "title": "Bytes received in ingester per second",
   "type": "graph",
   "description": "The total number of uncompressed bytes received per tenant.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
    }
   ]
  },
  {
   "title": "status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (app,status_code) (rate(loki_request_duration_seconds_count)[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Loki memory usage",
   "type": "graph",
   "description": "Percentage of actual usage over configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(container_memory_working_set_bytes{container=~\"table-manager|querier|logcli|query-frontend|compactor|distributor|query-scheduler\"})[1m] / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Promtail memory usage",
   "type": "timeseries",
   "description": "Percentage of actual usage over configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pod,container) (container_memory_working_set_bytes{pod=~\"promtail.*\"}) / 1024 /1024  / 1024 ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Loki CPU usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Promtail CPU usage (% of Kubernetes limit)",
   "type": "timeseries",
   "description": "percentage of configured limit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"promtail.*\"}[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}