{
 "title": "Logging Dashboard via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging",
  "main"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "k8s_app",
    "label": "k8s_app",
    "query": "label_values({source=~\"$source\"},k8s_app)"
   },
   { "name": "source", "label": "source", "query": "label_values(source)" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   { "name": "nodename", "label": "nodename", "query": "label_values(nodename)" },
   {
    "name": "syslog_identifier",
    "label": "syslog_identifier",
    "query": "label_values({source=~\"$source\"},syslog_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Searched logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{source=~\"$source\",nodename=~\"$nodename\",k8s_app=~\"$k8s_app\",syslog_identifier=~\"$syslog_identifier\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"})[$__interval])) by (source)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (k8s_app)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{source=~\"$source\",nodename=~\"$nodename\",k8s_app=~\"$k8s_app\",syslog_identifier=~\"$syslog_identifier\"}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (k8s_app)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({nodename=~\"$nodename|\", source=\"$source\", k8s_app=~\"$k8s_app|\",syslog_identifier=~\"$syslog_identifier|\"} |~ \"(?i)$searchable_pattern\")[30s])) by (k8s_app)"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({k8s_app=~\"$k8s_app\"})[$__interval])) by (source)"
    }
   ]
  }
 ]
}