{
 "title": "Loki s3",
 "tags": [
  "loki",
  "monitoring loki",
  "s3",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lines Per Tenant (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_lines_received_total[5m])) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "MBs Per Tenant (Top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)) / 1024 / 1024",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(loki_s3_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(loki_s3_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(loki_s3_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  {
   "title": "Status By Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_s3_request_duration_seconds_count[5m])) by (status_code, operation)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  },
  { "title": "BoltDB Shipper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(loki_boltdb_shipper_store_gateway_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(loki_boltdb_shipper_store_gateway_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(loki_boltdb_shipper_store_gateway_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  {
   "title": "Status By Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_boltdb_shipper_store_gateway_request_duration_seconds_count[5m])) by (status_code, operation)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  }
 ]
}