{
 "title": "k8s-event",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "type",
    "query": {
     "query": "label_values(kube_event_unique_events_total,type)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_event_unique_events_total,namespace)"
    }
   },
   {
    "name": "kind",
    "label": "kind",
    "query": {
     "query": "label_values(kube_event_unique_events_total{namespace=~\"$namespace\",type=~\"$type\"},involved_object_kind)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(kube_event_unique_events_total{involved_object_kind=~\"$kind\",namespace=~\"$namespace\"},involved_object_name)"
    }
   },
   {
    "name": "reason",
    "label": "reason",
    "query": {
     "query": "label_values(kube_event_unique_events_total{involved_object_kind=~\"$kind\",namespace=~\"$namespace\"},reason)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "count by type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_event_count) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count by reason",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_event_count) by (reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count by object",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_event_count) by (involved_object_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count by namespace",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_event_count) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "                                                                                                        below with vars"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "count events by vars",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_event_unique_events_total{namespace=~\"$namespace\",type=~\"$type\",involved_object_kind=~\"$kind\",involved_object_name=~\"$name\"}) by (type,involved_object_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reason by namespace $namespace",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_event_unique_events_total{type=~\"$type\",namespace=~\"$namespace\",involved_object_kind=~\"$kind\"}) by (reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total events by reason $reason",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_event_unique_events_total{type=~\"$type\",namespace=~\"$namespace\",involved_object_kind=~\"$kind\",involved_object_name=~\"$name\",reason=~\"$reason\"})",
     "legendFormat": "kind - {{$kind}} with reason {{$reason}} "
    }
   ]
  },
  {
   "title": "events by vars",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_event_unique_events_total{namespace=~\"$namespace\",type=~\"$type\",involved_object_kind=~\"$kind\",involved_object_name=~\"$name\"}) by (type,involved_object_kind,involved_object_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count pods with reason $reason",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_event_unique_events_total{type=~\"$type\",namespace=~\"$namespace\",involved_object_kind=~\"$kind\",involved_object_name=~\"$name\",reason=~\"$reason\"})",
     "legendFormat": "total pods  with kind - {{$kind}}"
    }
   ]
  },
  {
   "title": "rate all event",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(kube_event_unique_events_total{namespace=~\"$namespace\",involved_object_kind=~\"$kind\"})) by (type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}