{
 "title": "Network Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "myinterval", "label": "interval", "query": "1m,5m,10m,15m,30m" },
   { "name": "type", "label": "type", "query": "va,be,hot,warm,aux,lb" },
   {
    "name": "instance",
    "label": "host",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{instance=~'.*$type.*'}, instance)"
    }
   },
   { "name": "device", "label": "interface", "query": "internal,private" }
  ]
 },
 "panels": [
  {
   "title": "Recieved",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~'$instance', device=~'$device'}[$myinterval])*8",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$instance', device=~'$device'}[$myinterval])*8",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Rx Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{instance=~'$instance', device=~'$device'}[$myinterval])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Rx Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_network_receive_errs_total{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Tx Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_errs_total{instance=~'$instance', device=~'$device'}[$myinterval])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Tx Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_network_transmit_errs_total{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  }
 ]
}