{
 "title": "Platform",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wait time write be",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\".*be.*\", device=~'.*rbd.*'}[5m]) / rate(node_disk_writes_completed_total{instance=~\".*be.*\", device=~'.*rbd.*'}[5m])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "reads wait be",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\".*be.*\", device=~'.*rbd.*'}[5m]) / rate(node_disk_reads_completed_total{instance=~\".*be.*\", device=~'.*rbd.*'}[5m])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "reads wait max hot|warm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(node_disk_read_time_seconds_total{instance=~\".*warm.*|.*hot.*\"}[5m]) / rate(node_disk_reads_completed_total{instance=~\".*warm.*|.*hot.*\"}[5m]))",
     "legendFormat": "reads waits"
    }
   ]
  },
  {
   "title": "wait time write max hot|warm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(node_disk_write_time_seconds_total{instance=~\".*hot.*|.*warm.*\"}[5m]) / rate(node_disk_writes_completed_total{instance=~\".*hot.*|.*warm.*\"}[5m]))",
     "legendFormat": "write wait"
    }
   ]
  },
  {
   "title": "ceph_osd_apply_latency_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "max(ceph_osd_apply_latency_ms)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ceph_osd_commit_latency_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(ceph_osd_commit_latency_ms)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}