{
 "title": "PostgreSQL Database Edited",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "mode",
    "label": "Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(pg_locks_count, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{cluster_name=\"lottery-main\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"postgres-lottery-main\",cluster_name=\"lottery-main\",kubernetes_pod_name=\"postgres-lottery-main-0\"} * 1000"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", kubernetes_pod_name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", kubernetes_pod_name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{kubernetes_pod_name=~\"$name\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{kubernetes_pod_name=~\"$name\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{kubernetes_pod_name=~\"$name\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{kubernetes_pod_name=~\"$name\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{kubernetes_pod_name=~\"$name\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{kubernetes_pod_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{kubernetes_pod_name=\"$name\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{kubernetes_pod_name=\"$name\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", mode=~\"$mode\", kubernetes_pod_name=~\"$name\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", kubernetes_pod_name=~\"$name\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", kubernetes_pod_name=~\"$name\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{kubernetes_pod_name=\"$name\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{kubernetes_pod_name=\"$name\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{kubernetes_pod_name=\"$name\", datname=~\"$datname\"} / (pg_stat_database_blks_read{kubernetes_pod_name=\"$name\", datname=~\"$datname\"} + pg_stat_database_blks_hit{kubernetes_pod_name=\"$name\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_total[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean_total[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", kubernetes_pod_name=~\"$name\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=\"$datname\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", kubernetes_pod_name=~\"$name\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{kubernetes_pod_name=\"$name\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  {
   "title": "Wal lag size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_replication_slots_pg_wal_lsn_diff",
     "legendFormat": "{{kubernetes_pod_name  }}"
    }
   ]
  },
  {
   "title": "replication lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{kubernetes_pod_name=~\"$name\"} ",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "$name volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"lottery\",persistentvolumeclaim=~\"postgres-lottery-.*-data-$name\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}